### PR TITLE
Update calls to wrenInterpret in documentation

### PR DESCRIPTION
**Pull request by jyaif**
wrenInterpret now takes a `const char* module` parameter.

### CODE REVIEW

**Comment by minirop** [comment]
why did you remove the carriage return in `System.print`?

**Comment by jyaif** [comment]
Ooops, I don't know how to use pull requests correctly.

**Comment by jyaif** [comment]
ptal

**Comment by mhermier** [comment]
On GitHub you pull request by branch. So you have to be careful branch
correctly and only reuse on branch to update a feature.

**Pull request closed without merging**
