### PR TITLE
Support for shebang.

### PR DESCRIPTION
**Pull request by mauvm**
This PR allows for a `#!` ("comment") on the first line of code.

I have put the `default` case in a separate function to avoid having to let the `'#'` case fall through.

The tests fail because of https://github.com/munificent/wren/pull/51#issuecomment-68582689 and #57.

### CODE REVIEW

**Comment by munificent** [comment]
This is really nice! I have a couple of suggestions, then I'll be delighted to merge this in.

**Comment by mauvm** [comment]
Thanks for the feedback. I have made the changes, but for some reason two of my tests still fail:

```
FAIL: test/number/divide.wren
      Expected output "nan" on line 7 and got "-nan".
      Expected output "nan" on line 8 and got "-nan".
      Expected output "nan" on line 11 and got "-nan".
      Expected output "nan" on line 12 and got "-nan".

FAIL: test/shebang/shebang_at_eof.wren
      Expected return code 0 and got 65. Stderr:
      [test/shebang/shebang_at_eof.wren line 1] Error on '': Unexpected token for expression.


FAIL: test/shebang/shebang_invalid.wren
      Unexpected error:
      [test/shebang/shebang_invalid.wren line 0] Error on '': Unexpected token for expression.
```

I believe the first one is the one you mentioned:  https://github.com/munificent/wren/pull/51#issuecomment-68582689.
The last two I can't really explain.. I think they're related to https://github.com/munificent/wren/issues/57.

**Comment by mauvm** [comment]
Thanks for the feedback. I have made the changes, but for some reason two of my tests still fail:

```
FAIL: test/number/divide.wren
      Expected output "nan" on line 7 and got "-nan".
      Expected output "nan" on line 8 and got "-nan".
      Expected output "nan" on line 11 and got "-nan".
      Expected output "nan" on line 12 and got "-nan".

FAIL: test/shebang/shebang_at_eof.wren
      Expected return code 0 and got 65. Stderr:
      [test/shebang/shebang_at_eof.wren line 1] Error on '': Unexpected token for expression.


FAIL: test/shebang/shebang_invalid.wren
      Unexpected error:
      [test/shebang/shebang_invalid.wren line 0] Error on '': Unexpected token for expression.
```

I believe the first one is the one you mentioned:  https://github.com/munificent/wren/pull/51#issuecomment-68582689.
The last two I can't really explain.. I think they're related to https://github.com/munificent/wren/issues/57.

**Comment by munificent** [comment]
You were half right. #57 was part of the problem (which I just fixed) and then there was another minor issue that a lexer error would also trigger a cascaded parser error. I fixed that too.

Thanks for this!

**Pull request merged**
