### PR TITLE
Refactor `runInterpreter`, which has 2 almost identical blocks, one in ...

### PR DESCRIPTION
**Pull request by patriciomacadden**
...`CASE_CODE(CALL_*)` and one in `CASE_CODE(SUPER_*)`.

Added a new macro named `CALL`. This time adding a macro makes sense because the refactored code uses macros defined in this function. If I'd extract this into a new static function it wouldn't work.

What do you think?

### CODE REVIEW

**Comment by munificent** [comment]
You are not the first to try to eliminate that redundancy. :)

Alas, it's not so simple. In my tests the last time I tried this, it had a significant negative perf impact, probably because of the `if` check.

This code is going to get less redundant in the future when I fix #250, so I wouldn't worry about it too much.

**Comment by patriciomacadden** [comment]
Oops!! I didn't look through old pull requests. My bad :cry:

**Comment by munificent** [comment]
> I didn't look through old pull requests.

No, it's totally fine. I don't think it would have even showed up in PRs. Most of this was either patches Michel emailed me or attempts I made that never got committed. It was a valiant attempt on your part. :)

**Comment by patriciomacadden** [comment]
It's not my intention to bring back this pull request alive, but I just run the benchmarks and I don't see much of a difference between this branch and master:

```
~/dev/oss/wren (refactor) ❯ script/benchmark.py -l wren
binary_trees - wren            .......... 0.36s 0.0122 no baseline
delta_blue - wren              .......... 0.15s 0.0042 no baseline
fib - wren                     .......... 0.38s 0.0037 no baseline
for - wren                     .......... 0.14s 0.0021 no baseline
method_call - wren             .......... 0.18s 0.0057 no baseline
map_numeric - wren             .......... 0.54s 0.0101 no baseline
map_string - wren              .......... 0.18s 0.0020 no baseline
string_equals - wren           .......... 0.37s 0.0075 no baseline
~/dev/oss/wren (refactor) ❯ git co master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
~/dev/oss/wren (master) ❯ script/benchmark.py -l wren
binary_trees - wren            .......... 0.36s 0.0106 no baseline
delta_blue - wren              .......... 0.15s 0.0034 no baseline
fib - wren                     .......... 0.37s 0.0057 no baseline
for - wren                     .......... 0.14s 0.0019 no baseline
method_call - wren             .......... 0.18s 0.0049 no baseline
map_numeric - wren             .......... 0.53s 0.0040 no baseline
map_string - wren              .......... 0.18s 0.0045 no baseline
string_equals - wren           .......... 0.37s 0.0082 no baseline
```

Did you run these benchmarks or other ones (maybe specific to `call` and `super`)?

**Comment by bjorn** [comment]
@patriciomacadden Just to make sure since I don't see it as part of your command line, did you remember to compile Wren in between the benchmarks?

**Comment by lluchs** [comment]
If you add --generate-baseline to the first benchmark.py invocation (but not the second), you'll get a nice colored comparison.

**Comment by patriciomacadden** [comment]
Hey @bjorn, nice point. I'm not used to compile interpreters, so I forgot to do it :stuck_out_tongue: 

Here it is the benchmark run again (with `--generate-baseline` in the first run, as @lluchs suggested):

```
~/dev/oss/wren (master) ❯ make clean
~/dev/oss/wren (master) ❯ make
        cc src/cli/io.c                   -Os -std=c99 -fPIC
        cc src/cli/main.c                 -Os -std=c99 -fPIC
        cc src/cli/vm.c                   -Os -std=c99 -fPIC
        cc src/vm/wren_compiler.c         -Os -std=c99 -fPIC
        cc src/vm/wren_core.c             -Os -std=c99 -fPIC
        cc src/vm/wren_debug.c            -Os -std=c99 -fPIC
        cc src/vm/wren_io.c               -Os -std=c99 -fPIC
        cc src/vm/wren_meta.c             -Os -std=c99 -fPIC
        cc src/vm/wren_primitive.c        -Os -std=c99 -fPIC
        cc src/vm/wren_utils.c            -Os -std=c99 -fPIC
        cc src/vm/wren_value.c            -Os -std=c99 -fPIC
        cc src/vm/wren_vm.c               -Os -std=c99 -fPIC
        cc bin/wren                       -Os -std=c99 -fPIC
        ar lib/libwren.a                  rcu
        cc lib/libwren.dylib              -Os -std=c99 -fPIC
~/dev/oss/wren (master) ❯ script/benchmark.py -l wren --generate-baseline
generating baseline
binary_trees - wren            .......... 0.38s 0.1343 no baseline
delta_blue - wren              .......... 0.15s 0.0177 no baseline
fib - wren                     .......... 0.38s 0.0300 no baseline
for - wren                     .......... 0.15s 0.0136 no baseline
method_call - wren             .......... 0.19s 0.0123 no baseline
map_numeric - wren             .......... 0.55s 0.0300 no baseline
map_string - wren              .......... 0.18s 0.0036 no baseline
string_equals - wren           .......... 0.38s 0.0090 no baseline
~/dev/oss/wren (master) ❯ git co refactor
Switched to branch 'refactor'
~/dev/oss/wren (refactor) ❯ make clean
~/dev/oss/wren (refactor) ❯ make
        cc src/cli/io.c                   -Os -std=c99 -fPIC
        cc src/cli/main.c                 -Os -std=c99 -fPIC
        cc src/cli/vm.c                   -Os -std=c99 -fPIC
        cc src/vm/wren_compiler.c         -Os -std=c99 -fPIC
        cc src/vm/wren_core.c             -Os -std=c99 -fPIC
        cc src/vm/wren_debug.c            -Os -std=c99 -fPIC
        cc src/vm/wren_io.c               -Os -std=c99 -fPIC
        cc src/vm/wren_meta.c             -Os -std=c99 -fPIC
        cc src/vm/wren_primitive.c        -Os -std=c99 -fPIC
        cc src/vm/wren_utils.c            -Os -std=c99 -fPIC
        cc src/vm/wren_value.c            -Os -std=c99 -fPIC
        cc src/vm/wren_vm.c               -Os -std=c99 -fPIC
        cc bin/wren                       -Os -std=c99 -fPIC
        ar lib/libwren.a                  rcu
        cc lib/libwren.dylib              -Os -std=c99 -fPIC
~/dev/oss/wren (refactor) ❯ script/benchmark.py -l wren
binary_trees - wren            .......... 0.37s 0.0173 103.06% relative to baseline
delta_blue - wren              .......... 0.15s 0.0123 101.26% relative to baseline
fib - wren                     .......... 0.38s 0.0418 100.38% relative to baseline
for - wren                     .......... 0.15s 0.0137 104.24% relative to baseline
method_call - wren             .......... 0.18s 0.0304 101.47% relative to baseline
map_numeric - wren             .......... 0.56s 0.0712  97.89% relative to baseline
map_string - wren              .......... 0.18s 0.0140 100.00% relative to baseline
string_equals - wren           .......... 0.39s 0.0299  96.33% relative to baseline
```

**Comment by bjorn** [comment]
So well, at least we can't say performance is an issue here.

For me personally, I find the macro way very hard to read and would much rather see a static function, but I guess it would need to receive a lot of parameters or some kind of context structure? And then of course if the compiler doesn't inline it there may be some performance effects...

Btw, I think within this code probably also lies the bug found as issue #250.

**Comment by munificent** [comment]
Yes, fixing #250 will definitely address this too since it probably means `super` calls will need to be handled entirely differently from regular method calls.

**Comment by patriciomacadden** [comment]
Agreed! Thanks everyone for taking your time to look at this :smile:

**Pull request closed without merging**
