### PR TITLE
First try at building separate lib + binary

### PR DESCRIPTION
**Pull request by pwoolcoc**
This makes it so a `make release` puts the `wren` binary in your `$PWD`, along with `libwren.a`, so that `wren` can be used more easily from other applications. (Also does similar things for `make debug`)

### CODE REVIEW

**Comment by munificent** [comment]
Oops, closed the wrong bug!

**Comment by munificent** [comment]
Thanks for hacking on this! This has been on my TODO list for a while. You'll have to spoonfeed this to me since I'm a total make novice. By:

> puts the wren binary in your $PWD,

do you mean something different from what it currently does, or just that it does the same thing for the shared lib now too?

**Comment by pwoolcoc** [comment]
No, it does the same thing for the `.a` now. `wren` and `wrend` will still show up in the same place as before.

**Comment by munificent** [comment]
Beautiful! Thank you very much!

This reminds me. I should really get an AUTHORS file going. Would you like to be in it? What name and email?

**Comment by pwoolcoc** [comment]
Sure! Paul Woolcock <paul@woolcock.us>

**Pull request merged**
