### PR TITLE
Set Object

### PR DESCRIPTION
**Pull request by Noctisdark**
Impelmented a Set type for wren, it uses a splay tree internally to represent the data.
It's *theoretically* blazing fast mostly due to the fact that its time complexity is **Amortized O(log n)**.

I tried to make the interface very simple and intuitive and provided a documentation with some primitive examples and a bit of details about how it work and what you should expect.

I'm actually excited about this pull request, and have some questions.
- Should I remove the comments and reformat the code ?
- What is the tree missing to be fully wren`ish? the interface is currenly very simple and only provides basic operations and lacks a lots of good ones.
- How can I improve it ?

Thanks ! :heart:

### CODE REVIEW

**Comment by JonesAndrew** [comment]
My understanding is that unique collections are usually implemented with dictionaries. Considering there is already a map type in wren it might be simpler to just take that route. I might take the time complexity stuff out of the docs, but other than that they seem very clean.

**Comment by Noctisdark** [comment]
@JonesAndrew thank you very much for the answer.
It's actually the other way around.
Maps are usuallly implemented as either hash-tables or self-balancing binary tree, C++ STL uses a red black tree for example. In wren it is map implemented as a `Sequence` which will not scale well, the difference between `O(n)` and `O(log n)` is very huge. for that even, maps should be reimplemented as hash table or trees.
The point of implementing `Set` for wren is to get better performance for dealing with unique comparable objects, if the time complexity is in the way, i'll glady remove It.

**Comment by bjorn** [comment]
> The point of implementing Set for wren is to get better performance for dealing with unique comparable objects, if the time complexity is in the way, i'll glady remove It.

Could be interesting to do a performance comparison between your Set implementation and a Set implemented as a thin wrapper around a Wren map.

**Comment by Noctisdark** [comment]
@bjorn great idea !
How should I hash integers, floats or arbitrary wren objects ?
The current implementation only uses string keys, right ?

**Comment by bjorn** [comment]
> How should I hash integers, floats or arbitrary wren objects ?
> The current implementation only uses string keys, right ?

I believe the Wren map takes any Wren value as key.

**Comment by bjorn** [comment]
See https://github.com/munificent/wren/blob/master/src/vm/wren_value.c#L416-L442

**Comment by Noctisdark** [comment]
@bjorn, deal!
 I'll run benchmarks soon on wren browser to decided the algorithmic performance.

**Comment by Noctisdark** [comment]
@bjorn 
I was just doing a speed test for `Set.insert` vs `Map[]=` and `Set.contains` vs `Map[]`.

Map and Set performed nearly as well for small inputs, less than 1000.
For larger inputs, map a lot faster larger inputs, 12 time faster for 1000000 insertion.

I'm guessing the penalty is coming from the fact that `Map` is mostly implemented in C which is a bit faster than Wren and that becomes significant when the number of operations blows up.

Thanks for the insights and sorry for taking your time.

**Comment by Noctisdark** [comment]
@bjorn, will surely do ! Thanks.

**Pull request closed without merging**
