### PR TITLE
Added -Wextra to Makefile, added check for allready freed in wrenFreeVm

### PR DESCRIPTION
**Pull request by verpeteren**
I had some time today, to pickup some TODO's in the code. As you can see, I am not quite comfortable with git yet. 

Basically: 

*  Added -Wextra to complile flags.
*  Added a check for allready freed in wrenFreeVm.

I hope that I am helping

### CODE REVIEW

**Comment by munificent** [comment]
>  As you can see, I am not quite comfortable with git yet.

I don't think even Linus is totally comfortable with Git. I really like the underlying functionality it supports, but its command-line interface is *terrible*.

This is a good opportunity to try to learn it a bit more. If it's OK with you, I'd like you to squash the commits here to a single one. That will make for a cleaner commit history when I merge it in. If you search for "git squash", you'll find a ton of resources. The one I like best is [this one](http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit). Can you try that out?

> I hope that I am helping

You totally are, thank you!

**Comment by verpeteren** [comment]
```I'd like you to squash the commits here to a single one.```

I just tried/did. Please verifiy

**Comment by munificent** [comment]
Hmm, I still see the original commits, and now also another change for changing some int types?

It looks like you're working out of the master branch of your fork of the repo, right? One thing that will probably make your (and by extension my :smile:) life easier is to use "feature branches". Basically, for each change you work on, you create a separate local Git branch.

This lets you create and manage separate pull requests for each one. (For example, here, checking for the freed VM, adding `-Wextra` would be separate branches.) It also keeps your master branch "clean" in that it doesn't contain any commits that didn't come from my repo. In other words, your master branch follows mine. (Your changes will appear in your master branch by me merging them in to *my* master branch and then you pulling the change *back* to your fork.)

My Git-fu could be stronger, but I *think* this will get you in shape:

First, we need to create feature branches for your changes:

```sh
# Start from a point without any of these changes.
git checkout f472a301a2

# Make a new branch for checking for the VM being freed.
git checkout -b free-vm

# Apply the commit for checking the freed VM to this branch.
git cherry-pick 369b3d0

# Make a new branch for the warnings changes.
git checkout f472a301a2
git checkout -b w-extra

# Apply the commit for changing the warnings to this branch.
git cherry-pick 47d402a

# Make a new branch for changing the int types.
git checkout f472a301a2
git checkout -b int-types
git cherry-pick 71ccf94 -Xours
```

The `-Xours` on the last one resolves a conflict between the int types commit and master at commit f472a301a2.

Next, we need to get your master branch back to a state where it doesn't have
any local changes and is up-to-date with mine. *If you have any other changes in there that aren't in this pull request, you'll want to do something like the above to capture them first.*

```sh
# "Roll back" your master branch to a point in time before any of your changes.
git checkout master
git reset --hard f472a301a2

# Pull over the latest changes from my repo.
# See: https://help.github.com/articles/syncing-a-fork/
git fetch upstream

# Update your master branch to match the upstream changes you just pulled over.
git merge upstream/master
```

If you scroll up past the changes, you should see "Fast-forward" in there after the last command. That's good. It means your master didn't have any other changes that didn't come from my repo.

Now you've got a clean, up-to-date master and three feature branches. The only problem now is that the parent commits for the feature branches are old. (In other words, you can think of them as patches against old versions of Wren.)

We need them be diffs against the latest code (which is now conveniently on master). We do that by "rebasing" them. That basically means "re-apply this patch from scratch on top of a new version of the code". Like so:

```sh
# Switch to a feature branch.
git checkout free-vm

# Replace its commit with a new one that patches the latest master.
git rebase master

# Do this for the other feature branches...
git checkout w-extra
git rebase master

git checkout int-types
git rebase master
```

Phew! I *think* this gets you back to a nice happy state. Now you can create separate pull requests for each change:

```sh
# Push all of the feature branches up to your fork of Wren on GitHub.
git push --all origin -u
```

Now use GitHub's UI to create pull requests for each of these branches.

I know this seems incomprehensively complex. Git gives you plenty of rope to hang yourself. Going forward, it should be a lot simpler for you. To most important step is to make sure you don't commit to master. As long as you do your local commits in separate branches, you'll avoid all of these headaches. The steps here just to get you *back* to a clean state.

The normal workflow is basically:

```
git checkout -b <feature name>
# Make change...
git commit

# Push it up to GitHub.
git push origin -u

# Create a pull request.
```

**Comment by bjorn** [comment]
I just have one small note about these git instructions since I saw them repeated several times:
```
git checkout f472a301a2
git checkout -b w-extra
```
Switching to a new branch based on a specific commit other than the current HEAD can be done easily in one step like:
```
git checkout -b w-extra f472a301a2
```
Nice, isn't it? I use it all the time.

**Comment by MarcoLizza** [comment]
> Nice, isn't it? I use it all the time.

I agree, is the single most useful git command one could use (granted it has too many arguments to be intuitive).

**Comment by munificent** [comment]
Thanks, @bjorn! I learned something new today! :smile:

I don't tend to use these commands much since I'm in the habit of making branches before I commit anything, so I haven't tried to learn how to optimize them.

**Pull request closed without merging**
