### PR TITLE
Changed maps size/capacity type

### PR DESCRIPTION
**Pull request by MarcoLizza**
That one is an easy one. :baby: Add coherence to the other length/size uses.

### CODE REVIEW

**Comment by MarcoLizza** [comment]
> Yep. Unfortunately, I know this. :sob:

As for the cache and data-alignment that could affect and boost/reduce the performance when applying modifications, I did some test by changing the `gcc` optimization flag to `-O3` (favouring speed over size).

It *seems* that noise fluctuations are reduces. Can you confirm this? (if it's worth the matter)

**Comment by munificent** [comment]
This pull request is a bit intertwined with [the list one](https://github.com/munificent/wren/pull/150/) and the commit history is getting a bit hairy. I know I asked you to separate them out, but would mind squashing the commits and combining these two into a single pull request? Here's what I'm thinking it would have:

* ObjList and ObjMap store their capacity as `uint32_t`.
* The list and map functions in wren_value.h/.c take `uint32_t`.
* `validateIndex()` in wren_core is changed to return `uint32_t` (it still takes `int` as a parameter).
* Any method in wren_core that takes a result from `validateIndex()` and passes it to a function in wren_value.c should be good. The remaining ones are `iterate()` in list and map. Those should check for a negative argument and return and only after that can we cast to a `uint32_t`.

How does that sound?

**Comment by munificent** [comment]
OK, I'm going to close these out for now since we have more important stuff to worry about. We'll still be able to use them for reference later if we decide to start worrying about numbers again. :)

**Comment by MarcoLizza** [comment]
I'll certainly merge the two branches into a single one, but for now I'll concentrate and on other stuff. ;)

**Pull request closed without merging**
