### PR TITLE
New System.puts

### PR DESCRIPTION
**Pull request by SteveVnzk**
I think we need System.print alternative without newline at end

### CODE REVIEW

**Comment by novabyte** [comment]
It would break backwards compatibility but it might be more consistent to have "print" and "println" rather than "puts" and "print". Depends on how @munificent feels about stdlib changes.

**Comment by bjorn** [comment]
Having `print` and `puts` like this would be especially confusing for people used to Ruby, where`puts` adds a newlines and `print` does not.

**Comment by SteveVnzk** [comment]
@bjorn you right, have idea for other name?

**Comment by SteveVnzk** [comment]
There is 2 ways
1) Create `println` and `print` (it would break backwards compatibility)
2) Choose right name, maybe from this list: `put`, `p`, `printc`, `format` (can by like `printf` in C)

**Comment by Noctisdark** [comment]
I guess it would be better to implement `System.printf`. Not only it would solve this problem, but it'll be a cool feature.

**Comment by ayosec** [comment]
`puts` is part of the [C standard library](https://en.wikibooks.org/wiki/C_Programming/C_Reference/stdio.h/puts). It works adding a `\n` at the end of the string. If wren adds a function like `puts`, it should do the same.

`println` and `print` (proposed by `SteveVnzk`) can be a better alternative.

If backward compatibility is critical, another option is `print` and `write`.

**Comment by SteveVnzk** [comment]
Ok, how say @Noctisdark, `printf` is solve this problem and cool feature, start work on it.

**Comment by munificent** [comment]
Something along these lines would be nice. I thought about `println()`, but it feels weird to give the longer name to what is typically the more common operation. `puts()` makes sense if you know the C standard lib, but it's probably not helpful if you don't.

Lua calls them `print()` (newline) and `write()` (no newline). What do you think of those?

**Comment by SteveVnzk** [comment]
`print()` and `write()` sounds good

**Pull request closed without merging**
