### PR TITLE
introduced docs auto publish step to travisci

### PR DESCRIPTION
**Pull request by CodogoFreddie**
As a user of wren, I want to be able to read up to date docs for wren online
As a potential contributor to wren, I want to know that my PRs to the docs will be useful.

This PR introduces a job to TravisCI to auto build and publish the wren docs to the `gh-pages` branch of the repo; ensuring the published docs stay up-to-date

### CODE REVIEW

**Comment by CodogoFreddie** [comment]
I've updated the travis config so the auto upload only runs on `master`, so we don't have WIP docs uploaded to the live site.

I should also mention that @munificent will need to create a github personal access token, and set it as a travis env variable named `GH_TOKEN`. You can generate a token [here](https://github.com/settings/tokens)

**Comment by munificent** [comment]
Thank you, this is really cool!

Sorry it took a while to get to this. It's always a little unnerving merging in something that (1) I can't verify locally and (2) requires credentials. *<sweats nervously>*

But after reading a bunch of Travis docs and scrutinizing this as closely as I could, it looks good to me.

**Comment by CodogoFreddie** [comment]
> Sorry it took a while to get to this. It's always a little unnerving merging in something that (1) I can't verify locally and (2) requires credentials.

I probably should have foreseen what a spooky thing this would be to merge. If it would make you feel any safer, it should be pretty quick and painless to create a new github user with `publish-to-repo` authorization, but no admin privileges, and give travis _their_ API key instead

**Comment by munificent** [comment]
Good suggestion, but I think what I have working now is OK. Doc generation is up and running. Thanks!

**Pull request merged**
