### PR TITLE
Vendor GYP and libuv into the repo.

### PR DESCRIPTION
**Pull request by munificent**
Instead of dynamically downloading these as needed during a build, this
checks in those two dependencies directly into the Wren repo. That's a
little lame because users of Wren who aren't building the CLI don't
actually need them, but they aren't too big, so it's not a huge deal.

It makes builds (particularly on Travis) more reliable, because they
don't have to pull down additional content over the network.

### CODE REVIEW

**Comment by mhermier** [comment]
Built for me correctly on linux-x86_64.

While at it, speaking of libuv, I recently find and issue in wren code where libuv was using already free'd data. See the first patch of my change set:
https://github.com/mhermier/wren/commit/b5f74dcf186b291184664248260da7a5934c79c3 (libuv fixup.)
It seems libuv is taking care at freeing stdinStream, and will do it later, when hitting the event loop. So the extra free makes valgrind cries.

**Comment by Nelarius** [comment]
The Visual Studio solution will have to be updated, since it downloaded libuv into the project folder. I can submit a pr for that a bit later.

**Comment by Nelarius** [comment]
Argh, it seems like `vcbuild.bat` wants to build everything, tests included, even though we don't run them. There's only one `msbuild` incantation in there, and it's for the entire solution. 😕

Maybe there's a work-around, it would be a bit of a bummer to have to include **all** of libuv.

**Comment by paulsapps** [comment]
Hmm.. wouldn't a sub module make more sense instead of adding it to the wren repo itself? It will be counted in the LOC etc.

**Comment by kirbyfan64** [comment]
@paulsapps Because then it's still being cloned, therefore it still counts towards the bandwith limit (#437).

**Comment by bjorn** [comment]
> @paulsapps Because then it's still being cloned, therefore it still counts towards the bandwith limit (#437).

But only Gyp suffered from a bandwidth limited repository, not libuv.

I would suggest to only include Gyp in the repository.

**Comment by paulsapps** [comment]
A submodule on github will not have that problem @kirbyfan64  if it did then cloning the wren repo itself will too. By submodule I mean git submodule on github - a mirror.

**Pull request merged**
