### PR TITLE
new typeof keyword

### PR DESCRIPTION
**Pull request by minirop**
I've added a new keyword `typeof` that returns the type of the expression as a string (`typeof(4+3) == Num`). Can be useful for error messages:

```cpp
class Plane {
  pilot=(value) {
    if(!(value is Pilot)) {
      IO.print("Error: 'Pilot' expected got '", typeof(value), "'.")
    }
  }
}

var p = new Plane
p.pilot = 3 // print "Error: 'Pilot' expected got 'Num'."
```

if you (Bob or any Wren-user) have any comment, remark, anything, feel free!

ps: I couldn't run the tests (yay, windows!), but I assume I didn't broke anything and wrote the new tests properly.

### CODE REVIEW

**Comment by bjorn** [comment]
Personally, I think I would expect `typeof` to return the type of its argument rather than the name of the type.

**Comment by minirop** [comment]
I thought about the JS `typeof` while writing the thing (and I'm not fully fluent in Wren), but that's probably a better option.

**Comment by bjorn** [comment]
Hmm, on second thought I'm afraid this just needlessly duplicates `Object.type`. Or do you see any advantage of having this as a keyword?

**Comment by minirop** [comment]
none, I just didn't know that existed. (but nonetheless it was fun hacking wren internal).

**Comment by munificent** [comment]
Yup, like @bjorn says, this is redundant with `.type`. I'm still glad you tried this out though, because I'm sure it's a good learning experience. :)

**Pull request closed without merging**
