### PR TITLE
C++ warnings

### PR DESCRIPTION
**Pull request by MarcoLizza**
Some minor fixes:
* when compiling as C++ with GCC there were some blocking warnings due to (missing) `const` string modifier;
* I've added the current working directory detection.

### CODE REVIEW

**Comment by munificent** [comment]
Thanks for cleaning this up! Instead of having to detect the platform, I did the simpler thing. I realized if you want a path relative to the cwd, the easiest way to get that is... just a relative path. :)

**Comment by MarcoLizza** [comment]
> I realized if you want a path relative to the cwd, the easiest way to get that is... just a relative path. :)

True.

But will this work even when running Wren from within (for example) the home directory while the executable itself resides in (let's say) `/usr/bin`?

**Comment by munificent** [comment]
> But will this work even when running Wren from within (for example) the home directory while the executable itself resides in (let's say) /usr/bin?

Yup! The cwd is based on what the cwd was when the executable was started, not the directory containing the executable itself.

**Comment by MarcoLizza** [comment]
Goody-goody.

That's what I expected, too. Fine.

**Pull request merged**
