### PR TITLE
Fix compilation on gcc8 and improve memory safety

### PR DESCRIPTION
**Pull request by megous**

### CODE REVIEW

**Comment by bjorn** [comment]
The readme says that Wren compiles cleanly as C++98, and `snprintf` was only standardized in C99 and C++11. Maybe Wren should simply only support C99 and C++11, not sure what the reason is behind sticking to C++98.

**Comment by minirop** [comment]
if was already discussed in #531 (and is still C++98-compliant), but I've still yet to find why gcc <= 7 doesn't complain (this warning wasn't implemented before?)

**Comment by megous** [comment]
@minirop There are several new warning categories in gcc 8. Often times it is false positive, because it doesn't catch all precautions that the programmer can make around various "unsafe" functions that makes the call safe.

**Comment by avivbeeri** [comment]
Is there a resolution for this issue? These warnings halt the build for me.

**Comment by minirop** [comment]
> Is there a resolution for this issue? These warnings halt the build for me.

one easy *fix*(?), is to add "+2" for the "message" size: `char message[ERROR_MESSAGE_SIZE + 2];`

**Comment by avivbeeri** [comment]
I've actually been doing this manually, but I was hoping for an upstream
fix :)

**Pull request closed without merging**
