### PR TITLE
Fix bug #362 calling Foreign methods

### PR DESCRIPTION
**Pull request by bytemaster**
I assume that invoking callForeign that the apiStack should be restored
to it's original value, rather than reset to NULL.

### CODE REVIEW

**Comment by aggsol** [comment]
*bump* Is this integrated any time soon?

**Comment by munificent** [comment]
Sorry I got so behind on stuff! The book sucked away all my free time, and I'm still trying to load balance them.

I think this fix is right, but I would love to have a test for it. If you wouldn't mind writing one, that would be great. If not, I can take a stab at it.

**Comment by bytemaster** [comment]
No time to write test, but can confirm that it is working in my own usage.

**Comment by munificent** [comment]
I'm always worried we'll regress untested code, but for now we should at least have the fix in. Thanks!

**Pull request merged**
