### PR TITLE
Abstract List's `toString` method to a more general `join` method on Sequence.

### PR DESCRIPTION
**Pull request by gsmaverick**

### CODE REVIEW

**Comment by lluchs** [comment]
I think join should be implemented for all Sequences. The if in the loop can also be eliminated by using iterators which may be better for performance.

**Comment by munificent** [comment]
Great idea!

**Comment by zeckalpha** [comment]
Does this solve #3?

**Comment by gsmaverick** [comment]
Thanks for all the comments, I've updated the PR to address them.

@zeckalpha This does not solve #3.

**Comment by munificent** [comment]
Awesome! I love all the tests. :grinning:

**Pull request merged**
