### PR TITLE
Fixes libuv build for systems where python is python3

### PR DESCRIPTION
**Pull request by krypt-n**
Fixed by using python2 when executing the libuv scripts.

### CODE REVIEW

**Comment by munificent** [comment]
This breaks users that don't have a `python2` executable (which includes me and I suspect many others). :(

Maybe it could check for the presence of `python2` first and use it and fall back to `python` if it's not defined?

**Comment by bjorn** [comment]
Ideally the scripts would support both Python 2 and 3, but I guess that'd be kinda hard.

**Comment by krypt-n** [comment]
Oh, I assumed that python2 is standard in python packages and the distributions I looked at confirmed that. I'll try finding a workaround

**Comment by munificent** [comment]
Thanks!

**Comment by krypt-n** [comment]
Updated, now uses the default python executable if the major version is 2.

**Comment by munificent** [comment]
Rad, thanks!

**Pull request merged**
