### PR TITLE
[critical] Fix getNumArguments and wrenBindMethodCode opcodes data.

### PR DESCRIPTION
**Pull request by mhermier**
Some instructions data in these 2 functions are out of syncs, and can try to
patch the code in bad manner.

I took the slower way in wrenBindMethodCode, to ease future maintenance. It is not a critical path, and it decouples patching from instruction walking.

### CODE REVIEW

**Comment by Akaricchi** [comment]
Could you add a test case?

**Comment by mhermier** [comment]
It is afaik not really possible to test case this. The only way would be to
compare disassembly, or inject specially crafted assembly to trigger the
issue in a controlled manner.
I wrote a private patch that test patching padding against padding made by
the internal disassembler. But quality wise and line of code change
required, it doesn't sounds the way to go.

**Comment by Akaricchi** [comment]
I'm interested in the private patch regardless of the quality -- for an educational experience, if nothing else. I've discovered Wren recently and I've been hacking on it myself the past few days.

**Comment by munificent** [comment]
Thank you!

**Pull request merged**
