### PR TITLE
8 bit clean

### PR DESCRIPTION
**Pull request by MarcoLizza**
Here's a preview of the modifications.

*(still needs more test cases, maybe)*

Also, as I wrote in a `TODO` comment, a better string matching algorithm should be implemented. Will work on the subject this evening.

### CODE REVIEW

**Comment by MarcoLizza** [comment]
I did some benchmarks to compare the naive brute-force (BF) algorithm with some "smarter" search algorithms, that is Quick-Search (QS), Knuth-Morris-Pratt (KMP), and Boyer-Moore-Horspool (BMH).

There can't be a definitive all-answer since the "best" algorithm heavily depends to the data itself.

On small strings BF is faster than the other (not requiring the initialization step). On longer strings, BMH behaves better on the average. BMH is also the cheaper one, with respect to the additional memory.

If we aim to have fast string operations I think we should go and use the naive algorithm for small strings and switch to BMH for longer ones. Defining the threshold could be difficult, although.

Thoughts?

**Comment by munificent** [comment]
This looks really awesome, but it's also a big pull request. I only get small pieces of free time, so it's hard for me to find enough time to handle this all at once. Do you think you could break it into separate smaller pull requests? Most of these commits could be standalone PRs, I think.

Thanks!

**Comment by MarcoLizza** [comment]
> Do you think you could break it into separate smaller pull requests? Most of these commits could be standalone PRs, I think.

Yep, will do.

Not every commit can be isolated in a single pull-request, but I'll do my best.

**Comment by MarcoLizza** [comment]
Done. We can close this pull-request and go for the other ones!

**Pull request closed without merging**
