### PR TITLE
Fixed char-subscripts warning

### PR DESCRIPTION
**Pull request by ComFreek**
See #245

### CODE REVIEW

**Comment by bjorn** [comment]
You should not open a new PR to make a fix. Generally, you amend your patch or you commit additional patches based on feedback, and then either force-push (in case of amending) or normal-push (in case of extra commits) to the same branch you had requested to be merged (so to the `patch-1` branch in your fork).

At this point, it is too late to do that, so this is just some information for next time. :-)

**Comment by ComFreek** [comment]
I didn't want to clutter the commit history and I learnt that [force-pushing could be dangerous](http://stackoverflow.com/questions/1270514/undoing-a-git-push#comment11064932_1270608) &mdash; at least in shared repos. According to your comment, I suppose the latter is usually not the case when submitting PRs.
Thanks for the info!

**Comment by bjorn** [comment]
> According to your comment, I suppose the latter is usually not the case when submitting PRs.

Right, a PR is explicitly a work-in-progress, and tweaks to the commits contained within are expected and a supported workflow, which requires force-pushing. It's also perfectly valid to just push additional commits, but as you say this can clutter the history.

**Comment by munificent** [comment]
Thanks!

**Pull request merged**
